"""add per-motion model choice

Revision ID: 7bfd0249f284
Revises: 2b7b9e771ce9
Create Date: 2026-08-08 15:21:52.531292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfd0249f284'
down_revision = '2b7b9e771ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motions', schema=None) as batch_op:
        batch_op.drop_column('model')

    # ### end Alembic commands ###
