"""users, motions, chat messages

Revision ID: f99b0329ca31
Revises: 
Create Date: 2026-08-08 14:02:22.232303

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f99b0329ca31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('encrypted_openai_key', sa.Text(), nullable=True),
    sa.Column('encrypted_anthropic_key', sa.Text(), nullable=True),
    sa.Column('openai_key_masked', sa.String(length=32), nullable=True),
    sa.Column('anthropic_key_masked', sa.String(length=32), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('motions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('motion_text', sa.Text(), nullable=True),
    sa.Column('position', sa.String(length=2), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('stage_1_document', sa.Text(), nullable=True),
    sa.Column('stage_2_document', sa.Text(), nullable=True),
    sa.Column('stage_3_document', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("position IN ('OG','OO','CG','CO')", name='ck_motions_position'),
    sa.CheckConstraint("provider IN ('openai','anthropic')", name='ck_motions_provider'),
    sa.CheckConstraint('current_stage BETWEEN 1 AND 3', name='ck_motions_stage'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('motions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_motions_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_motions_user_updated', ['user_id', 'updated_at'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('motion_id', sa.Uuid(), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user','assistant')", name='ck_messages_role'),
    sa.CheckConstraint('stage BETWEEN 1 AND 3', name='ck_messages_stage'),
    sa.ForeignKeyConstraint(['motion_id'], ['motions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_messages_motion_stage', ['motion_id', 'stage', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_messages_motion_stage')

    op.drop_table('chat_messages')
    with op.batch_alter_table('motions', schema=None) as batch_op:
        batch_op.drop_index('ix_motions_user_updated')
        batch_op.drop_index(batch_op.f('ix_motions_user_id'))

    op.drop_table('motions')
    op.drop_table('users')
    # ### end Alembic commands ###
