"""Stage-scoped system prompts.

`idea.md` is split into a shared section plus one section per stage, so a turn
sends only the rules that apply to it rather than the whole ~70KB document.
The split files live in app/prompts/ and are regenerated by
scripts/split_prompts.py.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path

PROMPT_DIR = Path(__file__).resolve().parent.parent / "prompts"

FIRST_TURN_INSTRUCTIONS = """
## This turn

The user has just stated their motion and position. In addition to producing the
Stage 1 document, extract the motion text and the BP position (OG, OO, CG, or CO)
from their message, and write a 3-6 word title for the sidebar.

If the user's message does not clearly contain both a motion and a position, do
not guess: ask for whichever is missing in `reply`, return an empty `document`,
and leave `motionText`/`position` as your best reading of what they did give.
""".strip()

ADVANCE_INSTRUCTIONS = """
## This turn

The previous stage is now final and is included above. Produce the opening
document for this stage by working from it. There is no new user message to
respond to — use `reply` to briefly tell the user what you have just produced
and what they might refine next.
""".strip()


@lru_cache(maxsize=8)
def _read(name: str) -> str:
    path = PROMPT_DIR / name
    if not path.exists():
        raise FileNotFoundError(
            f"Prompt file {path} is missing. Regenerate the prompt split with:\n"
            f"    python backend/scripts/split_prompts.py"
        )
    return path.read_text(encoding="utf-8").strip()


def system_prompt(stage: int, *, motion_text: str | None = None, position: str | None = None) -> str:
    """Assemble the system prompt for one stage.

    Shared rules (the Ordinary Intelligent Voter standard and the Argument
    Format) are included every time; the stage sections are not.
    """
    if stage not in (1, 2, 3):
        raise ValueError(f"Invalid stage: {stage}")

    parts = [_read("shared.md"), _read(f"stage{stage}.md")]

    if motion_text and position:
        parts.append(
            f"## This motion\n\n"
            f"Motion: {motion_text}\n"
            f"You are preparing arguments for: {position}\n\n"
            f"Every argument you produce must be one this position can actually "
            f"run, given its role in the round."
        )

    return "\n\n---\n\n".join(parts)
